### ISSUE TITLE
CAPK should look for `infraClusterSecret` in the `KubevirtCluster` resource namespace by default

### ISSUE THREAD

**Issue by pjaton** [kubernetes-sigs/cluster-api-provider-kubevirt#165]
**What steps did you take and what happened:**

Request the creation of a cluster in an external infrastructure providing the kubeconfig in a secret in the same namespace where the cluster spec resources are created and omitting the `Namespace` field in the `KubevirtCluster.spec.infraClusterSecretRef`.

E.g. with a ``KubevirtCluster` like the following one

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
    name: pja-multi
spec:
    infraClusterSecretRef:
        apiVersion: v1
        kind: Secret
        name: external-infra-kubeconfig
```

CAPK controller-manager will fail to reconcile the creation of the cluster and report in the log that it cannot find the `external-infra-kubeconfig`.

**What did you expect to happen:**

The `Namespace` field is optional in all the resource references used by CAPI. If the namespace is not specified, then the default behavior is to look for the referenced resource in the same namespace and the referring one. We should have the same logic here.

**Anything else you would like to add:**

This is due to the logic in [/pkg/infracluster/infracluster.go #GenerateInfraClusterClient](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/a8097c471d38aabe38179cd187a4d95618a834d2/pkg/infracluster/infracluster.go#L36) that does not check whether the `Namespace` field is set or not. It the latter case, it should fallback and looked in the provided `ownerNamespace`.

**Environment:**

- Cluster-api version: **v1beta1**
- Cluster-api-provider-kubevirt version: **v1alpha1**
- Kubernetes version: (use `kubectl version`): **v1.20.15**
- KubeVirt version: **v1**
- OS (e.g. from `/etc/os-release`): **CentOS 7**

/kind bug
