### ISSUE TITLE
controlPlaneEndpoint not used by kubevirtcluster controller

### ISSUE THREAD

**Issue by aamoyel** [kubernetes-sigs/cluster-api-provider-kubevirt#218]
**What steps did you take and what happened:**
I've tried to bootstrap a new cluster with a specific Control Plane endpoint (for testing purpose) and contrary to the "KubevirtCluster" CRD, My static endpoint is not used and ClusterIP Service address appear in controllers logs.
Here is my configuration:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: sailor-test
  namespace: sailor-test
spec:
  # Remote Kubevirt Cluster
  infraClusterSecretRef:
    apiVersion: v1
    kind: Secret
    name: kubevirt-kubeconfig
  controlPlaneEndpoint:
    host: 10.132.0.29
    port: 32443
```

**What did you expect to happen:**
I expect that the bootstrap controller use my host and port (10.132.0.23:32443) to reach api-server of the new cluster. But currently controllers used ClusterIP addr.

This line in your code replace controlPlaneEndpoint values with LB external IP :
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/main/controllers/kubevirtcluster_controller.go#L164

**Environment:**

- Cluster-api version: v1.3.2
- Cluster-api-provider-kubevirt version: v0.1.4
- Kubernetes version: (use `kubectl version`): v1.26.1
- KubeVirt version: v0.58.0
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1

/kind bug
