### ISSUE TITLE
Can't specify VM image in Flatcar template

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api-provider-kubevirt#311]
Hi @gcezaralmeida.

Thanks for contributing a Flatcar template in https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/298.

I'm trying to use your template and am not clear how specifying the VM image should work. I understand that you intended for the image to be in some PVC, however it's not clear to me how and where to create the PVC and how to copy the image to it.

IMO, it's much simpler to specify the image directly as follows:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-control-plane"
  namespace: "${NAMESPACE}"
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: "${NAMESPACE}"
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 2
                memory:
                  guest: "4Gi"
                devices:
                  networkInterfaceMultiqueue: true
                  disks:
                    - disk:
                        bus: virtio
                      name: containervolume
              evictionStrategy: External
              volumes:
                - containerDisk:
                    image: "${NODE_VM_IMAGE_TEMPLATE}"
                  name: containervolume
```

Could you clarify why it's important to use the PVC approach, as well as explain how it's supposed to be used?

Thanks in advance 🙏
