### ISSUE TITLE
Tenant cluster loadbalancer service is hardcoded to ClusterIP type

### ISSUE THREAD

**Issue by agradouski** [kubernetes-sigs/cluster-api-provider-kubevirt#64]
With ClusterIP type a tenant cluster will only be accessible within the same cluster, and cannot be exposed to external workloads.

Example load balancer service:
```
kvcluster-lb      ClusterIP   10.108.169.113   <none>        6443/TCP    4m56s
```

Currently, there's no way to configure the loadbalancer service, as the spec is hard coded.

**Comment by wangxin311** [comment]
My two cents:

do we want to expose load balancer service spec as a whole in KubevirtCluster?
>>: I think create a loadbalancer service as a whole is the easiest way to solve the problem, 
if the loadbalancer is available on the cluster, and Kubernetes will return both ClusterIP and LoadBalancerIP for the service, and return IP function in loadbalance.go can just return LoadBalancerIP, otherwise, Kubernetes will only return ClusterIP, and LoadbalancerIP will be shown as Pending, in this case,  return IP function in loadbalance.go will return ClusterIP like what we're doing today, but of cause the workload cluster is restricted access within the cluster.

will a simple service be sufficient for tenant cluster load balancing, or a more advanced implementation for load balancer is warranted?
>> IMO, simply Loadbalancer service is enough, administrator should responsible to manage/deploy Loadbalancer as separately.

**Comment by kewang-equinix** [comment]
There is one more issue we need address in order to support separate mgmt and workload cluster is to create VM service for each VirtualMachine and expose service as Loadbalancer and then return LB external IP instead of VM IP address to kubevirt cluster api, because mgmt cluster need to SSH into each VM to validate VM state to see if they're ready to join Kubernetes cluster but VM IP only visible within cluster, otherwise, capk-controller-manager may continuously complain  "Waiting for underlying VM to bootstrap..."

example yaml for VMI service should looks like this
```
apiVersion: v1
kind: Service
metadata:
  name: kvcluster121-control-plane-667lr-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    name: kvcluster121-control-plane-667lr
  type: LoadBalancer
```
