### ISSUE TITLE
Workload cluster VM is not able to resolve DNS entry

### ISSUE THREAD

**Issue by wangxin311** [kubernetes-sigs/cluster-api-provider-kubevirt#76]
/kind bug

we observed workload cluster is not able to pull docker image, and after look into the issue, seems the VM is not able to resolve DNS.

We're using the following qcow2 image for the Kubevirt VM, and kubernetes version is 1.21.0

NODE_VM_IMAGE_TEMPLATE=quay.io/kubevirtci/fedora-kubeadm:35

```
[root@kvcluster01-control-plane-8bgh9 capk]# ping www.google.com
ping: www.google.com: Name or service not known
[root@kvcluster01-control-plane-8bgh9 capk]# cat /etc/resolv.conf
# Generated by NetworkManager
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
```
I did tcpdump on cni0 interface of infra kubernetes cluster node, I didn't see any dns packet been received there.

If I add google DNS server `8.8.8.8` in /etc/resolv.conf file, then I am able to resolve dns entry.
```
[root@kvcluster01-control-plane-8bgh9 capk]# echo "nameserver 8.8.8.8" >> /etc/resolv.conf
[root@kvcluster01-control-plane-8bgh9 capk]# ping www.google.com
PING www.google.com (142.250.65.228) 56(84) bytes of data.
64 bytes from lga25s73-in-f4.1e100.net (142.250.65.228): icmp_seq=1 ttl=114 time=2.30 ms
64 bytes from lga25s73-in-f4.1e100.net (142.250.65.228): icmp_seq=2 ttl=114 time=2.36 ms
^C
--- www.google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 2.297/2.330/2.364/0.033 ms
```

I also tried the same image `quay.io/kubevirtci/fedora-kubeadm:35` with native kubevirt, everything works without adding `8.8.8.8`.

```
[root@fedora capk]# cat /etc/resolv.conf
# Generated by NetworkManager
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
[root@fedora capk]# ping www.google.com
PING www.google.com (142.251.40.132) 56(84) bytes of data.
64 bytes from lga25s80-in-f4.1e100.net (142.251.40.132): icmp_seq=1 ttl=113 time=2.45 ms
64 bytes from lga25s80-in-f4.1e100.net (142.251.40.132): icmp_seq=2 ttl=112 time=2.41 ms
```
here is my kubevirt vm yaml, FYI
```
root@ny5-infra04:~/kubevirt# cat vm.yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: fedora
  labels:
    vmi: http
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image:  quay.io/kubevirtci/fedora-kubeadm:35
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: capk
        chpasswd: { expire: False }
```
I am not sure what's the different the way kubevirt create VM and cluster-api create the VM, but it's surprise to me VM with native kubevirt works but not with cluster api kubevirt.

Thanks
Xin
